### PR TITLE
Bug fix

### LINKED ISSUE #6: Times of India single context is not fetching

### PR DESCRIPTION
**Pull request by azax25547**
#6 Fixed
Additional bug fixed
can be merged to master

### CODE REVIEW

File: src/controllers/affair.controller.js [hunk 1]
```diff
@@ -285,17 +289,16 @@ module.exports = {
                     introPara.push($(constants.selectors.introParagraphIE).text());
                     $(constants.selectors.restOfParagraphsIE).each((i, el) => restPara.push($(el).text()));
 
-                    responseJSON.data.context = introPara.concat(restPara).join("").trim();
+                    responseJSON.data.context = introPara.concat(restPara);
                     responseJSON.data.writtenBy = $(constants.selectors.writtenByIE).text();
                     responseJSON.data.introDescription = $(constants.selectors.introDescriptionIE).text()
                     responseJSON.success = true;
-
+                    console.log(responseJSON);
```
Comment (azax25547) [inline src/controllers/affair.controller.js:296]: must remove

**Review by azax25547 — COMMENTED** [review]
All the changes are fine
